version: '3.8'

services:

  database:
    container_name: GCES_Database
    hostname: library_db
    image: postgres
    ports:
      - "54321:5432"
    restart: unless-stopped
    env_file:
      - ./.env
