version: '3.8'

services:

  database:
    container_name: GCES_Database
    hostname: library_db
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    env_file:
      - ./.env

  server:
    container_name: GCES_Server
    build:
      dockerfile: ./library_back/Dockerfile
      context: ./
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - "database"

  client:
    container_name: GCES_Client
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./library_front
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - "database"
      - "server"

  nginx:
    container_name: GCES_Nginx
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - server