version: '3.8'

services:

  database:
    container_name: GCES_Database
    hostname: library_db
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    env_file:
      - ./.env

  server:
    container_name: GCES_Server
    build:
      dockerfile: ./library_back/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - "database"
