name: Django CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  DjangoCI:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies for flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint
        run: flake8 --max-line-length=254 --exclude migrations library_back
      - name: Build
        run: docker-compose up -d --build database server
      - name: Run Migrations
        run: docker exec GCES_Server bash -c "python manage.py migrate"
      - name: Test
        run: docker exec GCES_Server bash -c "python ./manage.py test"
