name: Django CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  DjangoCI:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies for flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint
        run: |
          flake8 --extend-ignore=E302,E101,E131,W191,W293,W292 --count --select=E9,F63,F7,F82 --exclude=*.pyc,*migrations* --show-source --statistics library_back/src/
          flake8 --extend-ignore=E302,E101,E131,W191,W293,W292 --count --max-complexity=10 --max-line-length=226 --exclude=*.pyc,*migrations* --statistics library_back/src/
      - name: Build
        run: |
          docker-compose down
          docker-compose up -d --build database server
      - name: Run Migrations
        run: docker exec GCES_Server bash -c "python manage.py makemigrations && python manage.py migrate"
      - name: Test
        run: docker exec GCES_Server bash -c "python ./manage.py test"
