name: React CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ReactCI:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          docker-compose up -d --build client
          docker exec GCES_Client npm run build
      
      - name: Lint
        run: docker exec GCES_Client npm run lint

      - name: Tests
        run: docker exec GCES_Client CI=true npm run test
        env:
          CI: true
