name: React CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ReactCI:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      # run: docker-compose up -d --build client
      # run: docker exec -it GCES_Client npm build
      run: npm build
    
    -name: Lint
      run: npm run lint

    - name: Tests
      # run: docker exec -it GCES_Client npm test
      run: npm test
